require:
- rubocop-minitest
- rubocop-rake
- rubocop-rspec

Lint/DuplicateMethods:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 300

Metrics/PerceivedComplexity:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

RSpec/ContextWording:
  AllowedPatterns:
  - "^and"

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
  - lib/asciidoctor-doctest.rb

Style/StringConcatenation:
  Enabled: false
