require 'asciidoctor/doctest'
require 'tilt'

DocTest::RakeTasks.new do |t|
  t.output_examples :html, path: 'examples/html'
  t.input_examples :asciidoc, path: %w[examples/asciidoc2 examples/asciidoc]
  t.converter = DocTest::HTML::Converter
  t.converter_opts = { template_dirs: 'templates' }
end
